apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels: 
        app: login
    spec:
      containers:
      - name: login-container
        image: vikasveldi/login-2502:v1.1
        ports:
        - containerPort: 80
