#Mutli Container pod concept

apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-fail
spec:
  containers:
  - name: nginx-cont-1
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx-cont-2
    image: nginx
    ports:
    - containerPort: 80
