apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-replicaset
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    labels:
      app: tomcat
spec:
  containers:
    - name: tomcat-container
      image: tomcat
      ports:
        - containerPort: 8080
